version: 2
jobs:
    test:
        docker:
            - image: openjdk:11
        environment:
            JAVAOPTIONS: "-Xms512m -Xmx2048m"
        steps:
            - checkout
            - run:
                  name: Build & Test
                  command: './mvnw clean test'
            - run:
                  name: Collect Test Results
                  command: |
                      mkdir test-results
                      find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} test-results/ \;
            - store_test_results:
                  path: test-results
    deploy:
        docker:
            - image: openjdk:11
        steps:
            - add_ssh_keys:
                  fingerprints:
                      - "ad:df:f7:20:05:10:5c:4a:d8:25:e5:42:c1:67:10:2a"
            - checkout
            - run:
                  name: Import GPG Key
                  command: gpg --batch --passphrase ${GPG_SIGNING_PASSWORD} --import .circleci/gpg.key.txt
            - run:
                  name: Configure Git
                  command: |
                      git config --global user.email "artifacts@smartling.com"
                      git config --global user.name "Smartling, Inc."
            - run:
                  name: Release
                  command: |
                      gpg --no-tty --batch --pinentry-mode loopback --passphrase ${GPG_SIGNING_PASSWORD} --clear-sign pom.xml
                      ./.circleci/release.sh
workflows:
    version: 2
    build_and_release:
        jobs:
            - test
            -  deploy:
                    requires:
                        - test
                    filters:
                        branches:
                            only: master

